#!/bin/bash

PATH_ROOT="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
CHANGELOG="$PATH_ROOT/revision.txt"

ENV=$1

if [[ -z "$SOURCE_COMMIT" ]]; then
	export SOURCE_COMMIT="${SOURCE_COMMIT:-$(git rev-parse HEAD)}"
    echo "$ENV:$SOURCE_COMMIT" | tee -i $CHANGELOG # -ai | write new line

    git add $CHANGELOG
fi

# "predev-build": "./.commit development",
# "preprod-build": "./.commit production",
# "prestage-build": "./.commit staging",
