export const label: string;
export const wrapper: string;
export const error: string;
export const hint: string;
export const clear: string;
export const control: string;
export const control_input: string;
export const control_textarea: string;
export const control_error: string;
