export const label: string;
export const wrapper: string;
export const error: string;
export const hint: string;
export const clear: string;
export const control: string;
export const controlInput: string;
export const controlTextarea: string;
export const controlError: string;
