module.exports = {
    Logo: require('components/logo'),
    Radio: require('components/radio'),
    Input: require('components/input'),
    Tabs: require('components/tabs'),
    Table: require('components/table'),
    Badge: require('components/badge'),
    Prompt: require('components/prompt'),
    Confirm: require('components/confirm'),
    Layout: require('components/layout'),
    Button: require('components/button'),
    Switch: require('components/switch'),
    Notify: require('components/notify'),
    Loader: require('components/loader'),
    Spinner: require('components/spinner'),
    Quantity: require('components/quantity'),
    Checkbox: require('components/checkbox'),
    HintText: require('components/hint-text'),
    Navigation: require('components/navigation'),
    MaskedText: require('components/masked-text'),
    RadioGroup: require('components/radio-group'),
    ColorPicker: require('components/color-picker'),
    BreadCrumbs: require('components/bread-crumbs'),
    SidebarIcon: require('components/sidebar-icon'),
    SuggestInput: require('components/suggest-input'),
    SelectionBox: require('components/selection-box'),
    CustomComponent: require('components/custom-component')
}
