'use strict';

const fs = require('fs');
const define = require('./define');
const { resolve } = require('path');

const config = {
    hash: false,
    cache: define.rs_production,
    inject: true,
    filetype: 'pug',
    production: define.rs_production,
    minify: define.rs_release && {
        keepClosingSlash: true,
        removeEmptyElements: false,
        removeComments: define.rs_production,
        decodeEntities: define.rs_production,
        customAttrAssign: define.rs_production,
        collapseWhitespace: define.rs_production,
        removeAttributeQuotes: define.rs_production,
        removeEmptyAttributes: define.rs_production,
        includeAutoGeneratedTags: define.rs_production,
        preventAttributesEscaping: define.rs_production,
        processConditionalComments: define.rs_production,
        removeRedundantAttributes: define.rs_production,
        removeScriptTypeAttributes: define.rs_production,
        removeStyleLinkTypeAttributes: define.rs_production,
        collapseBooleanAttributes: define.rs_production,
        collapseInlineTagWhitespace: define.rs_production,
        trimCustomFragments: define.rs_production,
        removeTagWhitespace: define.rs_production, // TEST MODE
        useShortDoctype: define.rs_production,
        minifyJS: define.rs_production,
        minifyCSS: define.rs_production,
        minifyURLs: define.rs_production
    }
}

const fileContent = function (filePath) {
    const content = fs.readFileSync(resolve(define.rs_base, filePath), 'utf8');
    return content.toString().replace(/<svg.*?>|<\/svg>/gi, '');
}

module.exports.fileContent = fileContent

module.exports.generateConfig = (script, template, chunksList) => {
    if (!template) {
        template = 'app';
    }

    config.template = [template, 'pug'].join('.');
    config.filename = resolve(define.rs_dist, [script, 'html'].join('.'));
    config.svgContext = fileContent('.cache/svgstore/svgstore.svg');

    if (chunksList !== undefined) {
        config.chunks = chunksList;
    }

    return config;
}
