'use strict';

const fs = require('fs');
const { resolve } = require('path');
const define = require('./define');

function fileContent(filePath) {
    const content = fs.readFileSync(resolve(define.rs_root, filePath), 'utf8');
    return content.toString().replace(/<svg.*?>|<\/svg>/gi, '');
}

module.exports.generateConfig = (script, template, chunksList) => {
    if (!template) {
        template = 'app';
    }

    const config = {
        hash: false,
        cache: define.rs_production,
        inject: true,
        filetype: 'pug',
        template: [template, 'pug'].join('.'),
        svgContext: fileContent('.cache/svgstore/svgstore.svg'),
        filename: resolve(define.rs_dist, [script, 'html'].join('.')),
        production: define.rs_production,
        minify: define.rs_release && {
            keepClosingSlash: true,
            removeEmptyElements: false,
            removeComments: define.rs_production,
            decodeEntities: define.rs_production,
            customAttrAssign: define.rs_production,
            collapseWhitespace: define.rs_production,
            removeAttributeQuotes: define.rs_production,
            removeEmptyAttributes: define.rs_production,
            includeAutoGeneratedTags: define.rs_production,
            preventAttributesEscaping: define.rs_production,
            processConditionalComments: define.rs_production,
            removeRedundantAttributes: define.rs_production,
            removeScriptTypeAttributes: define.rs_production,
            removeStyleLinkTypeAttributes: define.rs_production,
            collapseBooleanAttributes: define.rs_production,
            collapseInlineTagWhitespace: define.rs_production,
            trimCustomFragments: define.rs_production,
            removeTagWhitespace: define.rs_production, // TEST MODE
            useShortDoctype: define.rs_production,
            minifyJS: define.rs_production,
            minifyCSS: define.rs_production,
            minifyURLs: define.rs_production
        }
    }

    if (chunksList !== undefined) {
        config.chunks = chunksList;
    }

    return config;
}

module.exports.fileContent = fileContent
