export const title: string;
export const titleSizeNormal: string;
export const titleSizeMedium: string;
export const titleSizeSmall: string;
export const titleSizeBig: string;
export const title_primary: string;
export const titlePrimary: string;
export const title_secondary: string;
export const titleSecondary: string;
