export const group: string;
export const item: string;
export const item_default: string;
export const itemDefault: string;
export const item_inline: string;
export const itemInline: string;
export const label: string;
export const visible: string;
export const input: string;
