// export { Omit } from './type'
export { SvgFixer } from './svg-fixer'
export { renderRoute } from './render-route'
export { loadComponent } from './load-component'
export { renderDevTools } from './dev-tools'
export { OutsideClicked } from './outside-clicked'
