// export { Omit } from './type'
export { default as SvgFixer } from './svg-fixer'
export { default as renderRoute } from './render-route'
export { default as loadComponent } from './load-component'
export { default as renderDevTools } from './render-dev-tools'
export { default as OutsideClicked } from './outside-clicked'
