declare var __VERSION__: string
declare var __IN_DEBUG__: boolean

declare module 'hocs'
declare module 'store'
declare module 'utils'
declare module 'theme'
declare module 'config'
declare module 'assets'
declare module 'typings'
declare module 'helpers'
declare module 'layouts'
declare module 'helpers/api'
declare module 'helpers/get'
declare module 'helpers/store'
declare module 'helpers/token'
declare module 'helpers/compare'
declare module 'helpers/request'
declare module 'helpers/handlers'
declare module 'helpers/predicts'
declare module 'images'
declare module 'styles'
declare module 'scripts'
declare module 'svgstore'
declare module 'segments'
declare module 'settings'
declare module 'components'
declare module 'pages'
