declare var __VERSION__: string
declare var __IN_DEBUG__: boolean

declare module 'hocs'
declare module 'store'
declare module 'utils'
declare module 'theme'
declare module 'helpers'
declare module 'helpers/api'
declare module 'helpers/get'
declare module 'helpers/store'
declare module 'helpers/token'
declare module 'helpers/compare'
declare module 'helpers/request'
declare module 'helpers/handlers'
declare module 'helpers/predicts'
declare module 'segments'
declare module 'settings'
declare module 'components'
declare module 'pages'
